# -*- coding: utf-8 -*-
"""ddos_regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XnuGsYUUr1wD5dcxFLAPQ3XL8cWW63FI
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np
import re

log_file = "server.log"

timestamps = []

with open(log_file, "r") as file:
    for line in file:
        match = re.search(r"\[(.*?)\]", line)
        if match:
            timestamps.append(match.group(1))

df = pd.DataFrame(timestamps, columns=["timestamp"])
df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
df = df.dropna()

df["minute"] = df["timestamp"].dt.floor("min")
requests_per_minute = df.groupby("minute").size().reset_index(name="request_count")

requests_per_minute["time_index"] = np.arange(len(requests_per_minute))

X = requests_per_minute[["time_index"]]
y = requests_per_minute["request_count"]

model = LinearRegression()
model.fit(X, y)

pred = model.predict(X)

residuals = y - pred
threshold = residuals.mean() + 3 * residuals.std()

requests_per_minute["residual"] = residuals
requests_per_minute["is_ddos"] = residuals > threshold

plt.figure(figsize=(14,6))
plt.plot(requests_per_minute["minute"], y, label="Actual Traffic")
plt.plot(requests_per_minute["minute"], pred, label="Regression Line")
plt.xticks(rotation=45)
plt.legend()
plt.title("Web Traffic and Regression Analysis")

plt.savefig("ddos_plot.png")
plt.show()

ddos_intervals = requests_per_minute[requests_per_minute["is_ddos"]]

print("Potential DDoS Intervals:")
print(ddos_intervals[["minute", "request_count"]])